spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:file:C:\workspace\db
    password: ''

  h2:
    console:
      enabled: 'true'
      path: /h2
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
#  hibernate:
#    naming:
#      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl